apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata: { name: k8sforbidcurrentopt }
spec:
  crd: { spec: { names: { kind: K8sForbidCurrentOpt } } }
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package k8sforbidcurrentopt
      violation[{"msg": msg}] {
        input.review.kind.kind == "Deployment"
        some c
        c := input.review.object.spec.template.spec.containers[_]
        some e
        e := c.env[_]
        contains(lower(e.value), "/opt/mcp/current")
        msg := "forbidden: /opt/mcp/current in env values"
      }
      violation[{"msg": msg}] {
        input.review.kind.kind == "Deployment"
        some m
        m := input.review.object.spec.template.spec.containers[_].volumeMounts[_]
        contains(lower(m.mountPath), "/opt/mcp/current")
        msg := "forbidden: /opt/mcp/current mounted"
      }
