[package]
name = "rtt-sign"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519-dalek = "2"
rand = "0.8"
base64 = "0.22"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
